CREATE TABLE IF NOT EXISTS public.setor
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome_setor character varying(255) COLLATE pg_catalog."default",
    colaborador_id bigint,
    CONSTRAINT setor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.colaborador
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default",
    matricula bigint,
    nome character varying(255) COLLATE pg_catalog."default",
    perfil character varying(255) COLLATE pg_catalog."default",
    senha character varying(255) COLLATE pg_catalog."default",
    setor_id bigint,
    CONSTRAINT colaborador_pkey PRIMARY KEY (id),
    CONSTRAINT fkia1xdsbmy6pkus4mrgy90c3he FOREIGN KEY (setor_id)
        REFERENCES public.setor (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE public.setor
    ADD CONSTRAINT fk8lelx4cvsesevouaxu6f8kqki FOREIGN KEY (colaborador_id)
                           REFERENCES public.colaborador (id) MATCH SIMPLE
                           ON UPDATE NO ACTION
                           ON DELETE NO ACTION;


CREATE TABLE IF NOT EXISTS public.assunto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    assunto character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT assunto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.canal_comunicacao
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    canal character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT canal_comunicacao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.classificacao
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    classificacao character varying(255) COLLATE pg_catalog."default",
    dias_uteis integer NOT NULL,
    CONSTRAINT classificacao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.grau_parentesco
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    grau_parentesco character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT grau_parentesco_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.leito
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    leito character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT leito_pkey PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS public.tipo
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tipo character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tipo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.resposta_setor
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cumprimento_prazo character varying(255) COLLATE pg_catalog."default",
    data_resposta date,
    observacao character varying(255) COLLATE pg_catalog."default",
    resposta character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT resposta_setor_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.manifestacao
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ativo boolean NOT NULL,
    contato character varying(255) COLLATE pg_catalog."default",
    data_manifestacao date,
    paciente character varying(255) COLLATE pg_catalog."default",
    relato character varying(255) COLLATE pg_catalog."default",
    assunto_id bigint NOT NULL,
    canal_comunicacao_id bigint NOT NULL,
    classificacao_id bigint NOT NULL,
    grau_parentesco_id bigint NOT NULL,
    leito_id bigint NOT NULL,
    resposta_setor_id bigint NULL,
    setor_id bigint NOT NULL,
    tipo_id bigint NOT NULL,
    CONSTRAINT manifestacao_pkey PRIMARY KEY (id),
    CONSTRAINT fk57j2yqfmx3hfpvpt3nu0lx79v FOREIGN KEY (canal_comunicacao_id)
        REFERENCES public.canal_comunicacao (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk9r11tudh5y52pp3dvxt0p76ny FOREIGN KEY (setor_id)
        REFERENCES public.setor (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkca1qmcqt06h7owv0nbvlh3d0l FOREIGN KEY (classificacao_id)
        REFERENCES public.classificacao (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkdjyqs9rmuma08u9wjdr1oylew FOREIGN KEY (grau_parentesco_id)
        REFERENCES public.grau_parentesco (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkeqs1n3js8u79cco917g1ubh2l FOREIGN KEY (tipo_id)
        REFERENCES public.tipo (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkmd13f6q4uynffe0r8q4al0ln6 FOREIGN KEY (assunto_id)
        REFERENCES public.assunto (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkmn6m3qenspjraiyhnfow0ilu1 FOREIGN KEY (leito_id)
        REFERENCES public.leito (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkt0i8uop7socxpg21bcefc8dp FOREIGN KEY (resposta_setor_id)
        REFERENCES public.resposta_setor (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);



